[build]
builder = "docker"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
path = "backend"
builder = "docker"
dockerfile = "Dockerfile"
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 100

[[services]]
name = "frontend"
path = "frontend"
builder = "docker"
dockerfile = "Dockerfile"
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
